global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api
    static_configs:
      - targets: ['api:3000']
  - job_name: worker
    static_configs:
      - targets: ['worker:9464']
  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:9464']
